name: temp-CD.yml
on:
  push:
    branches:
      - temp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Actions에 Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 파일 만들기
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p src/main/resources/config
          printf '%s' "${{ secrets.APPLICATION_YML }}" > src/main/resources/config/application.yml

      - name: yml 존재 확인
        run: |
          ls -la src/main/resources/config
          echo "---- first lines ----"
          head -n 20 src/main/resources/config/application.yml
          cat src/main/resources/config/application.yml
      - name: Gradle Wrapper 권한 부여
        run: chmod +x ./gradlew


      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/cooltime-temp-server/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/cooltime-temp-server/current
            mkdir /home/ubuntu/cooltime-temp-server/current
            mv /home/ubuntu/cooltime-temp-server/tobe/project.jar /home/ubuntu/cooltime-temp-server/current/project.jar
            cd /home/ubuntu/cooltime-temp-server/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 & 
            rm -rf /home/ubuntu/cooltime-temp-server/tobe